"""Postgres (Supabase) access for courses, users, and saved chats."""

from __future__ import annotations

import atexit
import os
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator, Optional

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

load_dotenv(HERE / ".env")

SCHEMA = """
CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id TEXT, course_number TEXT, course_title TEXT, course_category TEXT,
    course_type TEXT, course_session TEXT, course_description TEXT, faculty_1 TEXT,
    faculty_1_email TEXT, faculty_bio TEXT, daytimes TEXT, timings_day TEXT,
    timings_start TEXT, timings_end TEXT, room TEXT, section TEXT, units TEXT,
    term_code TEXT, syllabus TEXT, old_syllabus TEXT,
    session_start_date TEXT, session_end_date TEXT, bid_or_permission TEXT
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Usernames are unique regardless of capitalization
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower ON users (lower(username));

CREATE TABLE IF NOT EXISTS chats (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_message TEXT NOT NULL,
    reply TEXT NOT NULL,
    tools_used JSONB NOT NULL DEFAULT '[]',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chats_user ON chats (user_id, id);

-- RLS with no policies keeps Supabase's public Data API out of these tables.
-- The backend connects as the database owner, which is not affected.
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE chats ENABLE ROW LEVEL SECURITY;
"""

_pool: Optional[ConnectionPool] = None


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        url = os.getenv("DATABASE_URL")
        if not url:
            raise RuntimeError(
                "DATABASE_URL is not set. Add your Supabase connection string to backend/.env."
            )
        kwargs = {"row_factory": dict_row, "prepare_threshold": None}
        if "sslmode" not in url:
            kwargs["sslmode"] = "require"
        _pool = ConnectionPool(url, min_size=1, max_size=5, kwargs=kwargs, open=True)
        atexit.register(_pool.close)
    return _pool


@contextmanager
def get_db() -> Iterator[psycopg.Connection]:
    """Borrow a pooled connection; commits on success, rolls back on error."""
    with _get_pool().connection() as conn:
        yield conn


def init_db() -> None:
    """Create any missing tables."""
    with get_db() as conn:
        conn.execute(SCHEMA)
